
package Interfaz;

import Dominio.Postulante;
import Dominio.Sistema;
import java.awt.Color;

import java.util.ArrayList;


import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.BorderFactory;


public class altaPostulante2 extends javax.swing.JPanel {

    private Sistema modelo;
    DefaultListModel<Object> Lmodelo = new DefaultListModel<>();
    private ArrayList<String> arrExp;

  
    public altaPostulante2() {
        initComponents();
    }

    public altaPostulante2(Sistema sis) {
        this.modelo = sis;
        arrExp = new ArrayList();
        initComponents();
        jLabelException.setVisible(false);

        for (int i = 0; i < modelo.getListaTematicas().size(); i++) {
            JCbTema.addItem(modelo.getListaTematicas().get(i));
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTbRegistrar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLExperiencia = new javax.swing.JList<>();
        JSpNivel = new javax.swing.JSpinner();
        JTbAgregar = new javax.swing.JToggleButton();
        JBEliminar = new javax.swing.JButton();
        JCbTema = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        JTbCancelar = new javax.swing.JToggleButton();
        jLabelException = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(850, 880));
        setPreferredSize(new java.awt.Dimension(850, 880));

        JTbRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTbRegistrar.setText("Registrar");
        JTbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTbRegistrarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(JLExperiencia);

        JSpNivel.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        JTbAgregar.setText("Agregar");
        JTbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTbAgregarActionPerformed(evt);
            }
        });

        JBEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JBEliminar.setText("Eliminar");
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });

        JCbTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbTemaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tema:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nivel:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Experiencia");

        JTbCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTbCancelar.setText("Cancelar");
        JTbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTbCancelarActionPerformed(evt);
            }
        });

        jLabelException.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelException.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JSpNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JCbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelException, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(JBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(JTbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JCbTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JSpNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTbAgregar))
                .addGap(57, 57, 57)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBEliminar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelException, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTbCancelar)
                    .addComponent(JTbRegistrar))
                .addContainerGap(418, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTbRegistrarActionPerformed

        jLabelException.setVisible(false);
        if (!Lmodelo.isEmpty()) {
            Postulante pos = modelo.getListaPostulantes().get(modelo.getListaPostulantes().size() - 1);
            for (int i = 0; i < arrExp.size(); i++) {
                int nivel = Integer.parseInt(arrExp.get(i).split("-")[1]);
                String nombre = arrExp.get(i).split("-")[0];
                modelo.registrarExperiencia(pos, nivel, nombre);
            }
            altaPostulante p = new altaPostulante(modelo);
            ((Menu) SwingUtilities.getWindowAncestor(this)).agregarPanel(p);
        } else {
            Border border = BorderFactory.createLineBorder(Color.RED, 2);
            JLExperiencia.setBorder(border);
            jLabelException.setVisible(true);
            jLabelException.setText("Complete las áreas indicadas");
        }

    }//GEN-LAST:event_JTbRegistrarActionPerformed

    private void JTbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTbAgregarActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        String aux = JCbTema.getSelectedItem().toString();
        JLExperiencia.setModel(Lmodelo);
        for(int i = 0;!flag && i<Lmodelo.getSize();i++){
            if(Lmodelo.get(i).toString().contains(aux)){
                flag = true;
            }
        }
        if (flag) {
            JOptionPane.showMessageDialog(null, "Ya ha ingresado una Temática con ese nombre");
        } else {
            Lmodelo.addElement(JCbTema.getSelectedItem().toString() + " (" + JSpNivel.getValue() + ")");
            arrExp.add(JCbTema.getSelectedItem().toString() + "-" + JSpNivel.getValue());

        }
    }//GEN-LAST:event_JTbAgregarActionPerformed

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        // TODO add your handling code here:
        try {
            Lmodelo.remove(JLExperiencia.getSelectedIndex());
            for (int i = 0; i < arrExp.size(); i++) {
                if (arrExp.get(i).split("-")[0].equals(JLExperiencia.getSelectedValue().toString())) {
                    arrExp.remove(i);
                    break;
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void JCbTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCbTemaActionPerformed

    private void JTbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTbCancelarActionPerformed
        // TODO add your handling code here:
        modelo.getListaPostulantes().remove(modelo.getListaPostulantes().size() - 1);
        altaPostulante p = new altaPostulante(modelo);
        ((Menu) SwingUtilities.getWindowAncestor(this)).agregarPanel(p);
    }//GEN-LAST:event_JTbCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEliminar;
    private javax.swing.JComboBox<Object> JCbTema;
    private javax.swing.JList<Object> JLExperiencia;
    private javax.swing.JSpinner JSpNivel;
    private javax.swing.JToggleButton JTbAgregar;
    private javax.swing.JToggleButton JTbCancelar;
    private javax.swing.JToggleButton JTbRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelException;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables


}
