
package Interfaz;

import Dominio.Sistema;
import Exceptions.Exception_ParseNumero;
import Exceptions.Exception_StringVacio;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.UIManager;


public class altaPostulante extends javax.swing.JPanel {

    private Sistema modelo;


    public altaPostulante() {
        initComponents();
    }

    public altaPostulante(Sistema miModelo) {
        this.modelo = miModelo;
        initComponents();
        jLabelException.setVisible(false);
        jLabeExcep1.setVisible(false);
        jLabelExcep2.setVisible(false);
        agregarRbGroup();
    }

    public void txtVacio() {
        jtxtNombre.setText("");
        jtxtId.setText("");
        jtxtDir.setText("");
        jtxtTel.setText("");
        jtxtMail.setText("");
        jtxtLink.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jtxtLink = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRbRemoto = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRbMixto = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRbPresencial = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jBSiguient = new javax.swing.JToggleButton();
        jtxtNombre = new javax.swing.JTextField();
        jtxtId = new javax.swing.JTextField();
        jtxtDir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtTel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtMail = new javax.swing.JTextField();
        jLabelExcep2 = new javax.swing.JLabel();
        jLabeExcep1 = new javax.swing.JLabel();
        jLabelException = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(850, 880));
        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cédula:");
        add(jLabel3);
        jLabel3.setBounds(55, 98, 100, 20);

        jtxtLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLinkActionPerformed(evt);
            }
        });
        add(jtxtLink);
        jtxtLink.setBounds(208, 303, 510, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Dirección:");
        add(jLabel4);
        jLabel4.setBounds(55, 150, 120, 20);

        jRbRemoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRbRemoto.setText("Remoto");
        jRbRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbRemotoActionPerformed(evt);
            }
        });
        add(jRbRemoto);
        jRbRemoto.setBounds(207, 355, 90, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono:");
        add(jLabel5);
        jLabel5.setBounds(55, 202, 80, 20);

        jRbMixto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRbMixto.setText("Mixto");
        add(jRbMixto);
        jRbMixto.setBounds(446, 355, 110, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mail:");
        add(jLabel6);
        jLabel6.setBounds(57, 254, 120, 20);

        jRbPresencial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRbPresencial.setText("Presencial");
        jRbPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbPresencialActionPerformed(evt);
            }
        });
        add(jRbPresencial);
        jRbPresencial.setBounds(323, 355, 110, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Linkedin:");
        add(jLabel7);
        jLabel7.setBounds(55, 306, 80, 20);

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        add(jBCancelar);
        jBCancelar.setBounds(60, 450, 100, 23);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Formato:");
        add(jLabel8);
        jLabel8.setBounds(55, 357, 90, 20);

        jBSiguient.setText("Siguiente");
        jBSiguient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiguientActionPerformed(evt);
            }
        });
        add(jBSiguient);
        jBSiguient.setBounds(600, 450, 110, 23);

        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });
        add(jtxtNombre);
        jtxtNombre.setBounds(210, 50, 510, 22);

        jtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdActionPerformed(evt);
            }
        });
        add(jtxtId);
        jtxtId.setBounds(208, 95, 510, 22);

        jtxtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDirActionPerformed(evt);
            }
        });
        add(jtxtDir);
        jtxtDir.setBounds(207, 147, 510, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alta Postulante");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 20));
        add(jLabel1);
        jLabel1.setBounds(-1, 10, 850, 25);

        jtxtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelActionPerformed(evt);
            }
        });
        add(jtxtTel);
        jtxtTel.setBounds(208, 199, 510, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        add(jLabel2);
        jLabel2.setBounds(55, 46, 90, 20);

        jtxtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMailActionPerformed(evt);
            }
        });
        add(jtxtMail);
        jtxtMail.setBounds(208, 251, 510, 22);

        jLabelExcep2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelExcep2.setText("blank");
        add(jLabelExcep2);
        jLabelExcep2.setBounds(210, 220, 370, 16);

        jLabeExcep1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabeExcep1.setText("blank");
        add(jLabeExcep1);
        jLabeExcep1.setBounds(210, 120, 370, 14);

        jLabelException.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelException.setText("jLabel4");
        add(jLabelException);
        jLabelException.setBounds(60, 390, 540, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLinkActionPerformed

    private void jRbRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbRemotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbRemotoActionPerformed

    private void jRbPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbPresencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbPresencialActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        Object[] opciones = {"Ok", "Cancelar"};
        String mensaje = "Si cancela se borraran todos los datos ";
        int opcionSeleccionada = JOptionPane.showOptionDialog(this,
                mensaje,
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones, opciones[1]);
        if (opcionSeleccionada == 0) {
            txtVacio();
            buttonGroup1.clearSelection();
        }


    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBSiguientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSiguientActionPerformed
        // TODO add your handling code here:
        jLabelException.setVisible(false);
        setBorderPainted(false);
        if (modelo.esCedulaValidaPos(jtxtId.getText())) {
            String formato = "";
            if (jRbRemoto.isSelected()) {
                formato = "Remoto";
            } else if (jRbPresencial.isSelected()) {
                formato = "Presencial";
            } else if (jRbMixto.isSelected()) {
                formato = "Mixto";
            }
            setDefaultBorder();
            try {
                modelo.registrarPostulante(jtxtNombre.getText(), jtxtId.getText(), jtxtDir.getText(), jtxtTel.getText(), jtxtMail.getText(), jtxtLink.getText(), formato);
                altaPostulante2 p = new altaPostulante2(modelo);
                ((Menu) SwingUtilities.getWindowAncestor(this)).agregarPanel(p);
            } catch (Exception_StringVacio ex) {
                Border border = BorderFactory.createLineBorder(Color.RED, 2);
                defbroder(border);
                if (formato.equals("")) {
                    setBorderPainted(true);
                    setBor(border);
                }
                jLabelException.setVisible(true);
                jLabelException.setText("Complete las áreas indicadas");
            } catch (Exception_ParseNumero ex) {
                jLabeExcep1.setText("Debe Ingresar un número");
                jLabeExcep1.setVisible(true);
                jLabelExcep2.setText("Debe Ingresar un número");
                jLabelExcep2.setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "La cédula que ingresó ya se encuentra en el sistema, intente denuevo");
        }
    }//GEN-LAST:event_jBSiguientActionPerformed

    private void setBorderPainted(Boolean b) {
        jRbMixto.setBorderPainted(b);
        jRbPresencial.setBorderPainted(b);
        jRbRemoto.setBorderPainted(b);
    }

    private void setDefaultBorder() {
        jtxtNombre.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtxtDir.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtxtTel.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtxtId.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtxtMail.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtxtLink.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jRbRemoto.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("RadioButton.border"));
        jRbMixto.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("RadioButton.border"));
        jRbPresencial.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("RadioButton.border"));
    }

    private void defbroder(Border border) {
        checkAndSetBorder(jtxtNombre, border);
        checkAndSetBorder(jtxtDir, border);
        checkAndSetBorder(jtxtId, border);
        checkAndSetBorder(jtxtTel, border);
        checkAndSetBorder(jtxtMail, border);
        checkAndSetBorder(jtxtLink, border);
    }

    private void agregarRbGroup() {
        buttonGroup1.add(jRbMixto);
        buttonGroup1.add(jRbPresencial);
        buttonGroup1.add(jRbRemoto);
    }

    private void setBor(Border border) {
        jRbMixto.setBorder(border);
        jRbPresencial.setBorder(border);
        jRbRemoto.setBorder(border);
    }

    private void checkAndSetBorder(JTextField textField, Border border) {
        if (textField.getText().equals("")) {
            textField.setBorder(border);
        }
    }
    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdActionPerformed

    private void jtxtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDirActionPerformed

    private void jtxtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelActionPerformed

    private void jtxtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JToggleButton jBSiguient;
    private javax.swing.JLabel jLabeExcep1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelExcep2;
    private javax.swing.JLabel jLabelException;
    private javax.swing.JRadioButton jRbMixto;
    private javax.swing.JRadioButton jRbPresencial;
    private javax.swing.JRadioButton jRbRemoto;
    private javax.swing.JTextField jtxtDir;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtLink;
    private javax.swing.JTextField jtxtMail;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtTel;
    // End of variables declaration//GEN-END:variables
}
