
package Interfaz;

import Dominio.Experiencia;
import Dominio.Postulante;
import Dominio.Sistema;
import Dominio.Tematica;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;


public class consultaTematica extends javax.swing.JPanel {

    private Sistema modelo;
    DefaultListModel<Postulante> Lmodelo = new DefaultListModel<>();

    public consultaTematica() {

        initComponents();
    }

    public consultaTematica(Sistema miModelo) {
        this.modelo = miModelo;
        initComponents();
        jListPost.setModel(Lmodelo);
        for (Tematica tem : modelo.getListaTematicas()) {
            jcbTematica.addItem(tem);
        }
        Tematica tematIni = (Tematica) jcbTematica.getSelectedItem();
        setearInfo(tematIni);
        jcbTematica.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Tematica tem = (Tematica) jcbTematica.getSelectedItem();
                setearInfo(tem);
                postulantesMayorNivel5();
            }
        });
        
        
    }
    private void setearInfo(Tematica tem){
        jLabelTematica.setText(tem.toString());
        jLabelTematica2.setText(tem.toString() + ": ");
        int cant = modelo.cantPuestosTematica(tem);
        jLabelRespuesta.setText(String.valueOf(cant));
        jLabelDescripcion.setText(tem.getDescripcion());
    }
    private void postulantesMayorNivel5(){
        for (int i = 0; i < modelo.getListaPostulantes().size(); i++) {
            Postulante pos = modelo.getListaPostulantes().get(i);
            if (pos.postulanteTieneExperienciaMayorNivel(5,(Tematica) jcbTematica.getSelectedItem())){
                Lmodelo.addElement(pos);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbTematica = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPost = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabelTematica = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTematica2 = new javax.swing.JLabel();
        jLabelRespuesta = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(850, 880));

        jcbTematica.setToolTipText("");
        jcbTematica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTematicaItemStateChanged(evt);
            }
        });
        jcbTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTematicaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta Tematica");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descripción");

        jScrollPane2.setViewportView(jListPost);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Postulantes con nivel mayor a 5 en");

        jLabelTematica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTematica.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad de puestos que requieren conocimiento en");

        jLabelTematica2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTematica2.setText("jLabel4");

        jLabelRespuesta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRespuesta.setText("Respuesta");

        jLabelDescripcion.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTematica))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTematica2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRespuesta))
                    .addComponent(jcbTematica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(jLabelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jcbTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelTematica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelTematica2)
                    .addComponent(jLabelRespuesta))
                .addContainerGap(348, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTematicaActionPerformed

    private void jcbTematicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTematicaItemStateChanged
        // TODO add your handling code here:
        Lmodelo.clear();
        jLabelTematica.setText(jcbTematica.getSelectedItem().toString());
        for (int i = 0; i < modelo.getListaPostulantes().size(); i++) {
            boolean flag = false;
            Postulante pos = modelo.getListaPostulantes().get(i);
            for (int j = 0; !flag && j < pos.getListaExperiencia().size(); j++) {
                Experiencia exp = pos.getListaExperiencia().get(j);
                if ((exp.getExperiencia().toString().equalsIgnoreCase(jcbTematica.getSelectedItem().toString())) && (exp.getNivel() >= 5)) {
                    flag = true;
                }
            }
            if (flag) {
                Lmodelo.addElement(pos);
            }
        }
    }//GEN-LAST:event_jcbTematicaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelRespuesta;
    private javax.swing.JLabel jLabelTematica;
    private javax.swing.JLabel jLabelTematica2;
    private javax.swing.JList<Postulante> jListPost;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Tematica> jcbTematica;
    // End of variables declaration//GEN-END:variables
}
