
package Interfaz;

import Dominio.Evaluador;
import Dominio.Postulante;
import Dominio.Sistema;
import Exceptions.Exception_StringVacio;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


public class ingresoEntrevista extends javax.swing.JPanel {

    private Sistema modelo;
    DefaultListModel<Object> Lmodelo1 = new DefaultListModel<>();
    DefaultListModel<Object> Lmodelo2 = new DefaultListModel<>();


    public ingresoEntrevista() {
        initComponents();
    }

    public ingresoEntrevista(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        jLPostulante.setModel(Lmodelo1);
        jLEvaluador.setModel(Lmodelo2);
        for (int i = 0; i < modelo.getListaPostulantes().size(); i++) {
            Lmodelo1.addElement(modelo.getListaPostulantes().get(i));
        }
        for (int i = 0; i < modelo.getListaEvaluadores().size(); i++) {
            Lmodelo2.addElement(modelo.getListaEvaluadores().get(i));
        }
        jLEvaluador.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    jLabelEvaluador.setText(jLEvaluador.getSelectedValue().toString());
                } catch (Exception a) {

                }
            }

        });
        jLPostulante.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    jLabelPostulante1.setText(jLPostulante.getSelectedValue().toString());
                } catch (Exception a) {

                }
            }

        });
        jLabelException.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLEvaluador = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        JLabelEvaluador = new javax.swing.JLabel();
        jLabelEvaluador = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTfPuntaje = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTaComentario = new javax.swing.JTextArea();
        jBIngresa = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabelPostulante1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLPostulante = new javax.swing.JList<>();
        jLabelException = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(850, 880));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso Entrevista");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 20));
        add(jLabel1);
        jLabel1.setBounds(-2, 6, 850, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione un Evaluador:");
        add(jLabel2);
        jLabel2.setBounds(30, 80, 340, 20);

        jScrollPane1.setViewportView(jLEvaluador);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 340, 170);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione un postulante:");
        add(jLabel3);
        jLabel3.setBounds(480, 80, 310, 20);
        add(JLabelEvaluador);
        JLabelEvaluador.setBounds(187, 200, 0, 0);

        jLabelEvaluador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEvaluador.setText("Seleccione un evaluador");
        add(jLabelEvaluador);
        jLabelEvaluador.setBounds(30, 320, 340, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Puntaje (0 - 100):");
        add(jLabel6);
        jLabel6.setBounds(30, 370, 130, 20);
        add(jTfPuntaje);
        jTfPuntaje.setBounds(170, 370, 640, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Comentarios:");
        add(jLabel7);
        jLabel7.setBounds(30, 430, 130, 20);

        jTaComentario.setColumns(20);
        jTaComentario.setRows(5);
        jScrollPane3.setViewportView(jTaComentario);

        add(jScrollPane3);
        jScrollPane3.setBounds(170, 430, 640, 100);

        jBIngresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBIngresa.setText("Ingresar");
        jBIngresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresaActionPerformed(evt);
            }
        });
        add(jBIngresa);
        jBIngresa.setBounds(720, 590, 90, 27);

        jBCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        add(jBCancelar);
        jBCancelar.setBounds(30, 590, 130, 27);

        jLabelPostulante1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPostulante1.setText("Seleccione un postulante");
        add(jLabelPostulante1);
        jLabelPostulante1.setBounds(480, 320, 310, 20);

        jScrollPane4.setViewportView(jLPostulante);

        add(jScrollPane4);
        jScrollPane4.setBounds(480, 110, 310, 170);

        jLabelException.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelException.setText("jLabel4");
        add(jLabelException);
        jLabelException.setBounds(30, 560, 540, 14);
    }// </editor-fold>//GEN-END:initComponents


    private void jBIngresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresaActionPerformed
        setDefaultBorder();
        jLabelException.setVisible(false);
        try {
            Postulante pos = (Postulante) jLPostulante.getSelectedValue();
            int puntaje = Integer.parseInt(jTfPuntaje.getText());
            if (puntaje > 0 && puntaje <= 100) {
                modelo.registrarEntrevista((Evaluador) jLEvaluador.getSelectedValue(), (Postulante) jLPostulante.getSelectedValue(), jTfPuntaje.getText(), pos.getListaEntrevistas().size() + 1, jTaComentario.getText());
                txtVacio();
            } else {
                pintarBordesExepcion();
                setLabelExceptionVisible();
            }
        } catch (Exception_StringVacio ex) {
            pintarBordesExepcion();
            setLabelExceptionVisible();

        } catch (NullPointerException ex) {
            setLabelExceptionVisible();
            pintarBordesExepcion();
        } catch (NumberFormatException ex) {
            pintarBordesExepcion();

        }

    }//GEN-LAST:event_jBIngresaActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        Object[] opciones = {"Ok", "Cancelar"};
        String mensaje = "Si cancela se borraran todos los datos ";
        int opcionSeleccionada = JOptionPane.showOptionDialog(this,
                mensaje,
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones, opciones[1]);
        if (opcionSeleccionada == 0) {
            txtVacio();

        }

    }//GEN-LAST:event_jBCancelarActionPerformed
    private void setDefaultBorder() {
        jTfPuntaje.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jLEvaluador.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jLPostulante.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jTaComentario.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
    }

    private void setLabelExceptionVisible() {
        jLabelException.setVisible(true);
        jLabelException.setText("Complete los campos indicados");
    }

    private void pintarBordesExepcion() {
        Border border = BorderFactory.createLineBorder(Color.RED, 2);
        try {
            int puntaje = Integer.parseInt(jTfPuntaje.getText());
            if (jTfPuntaje.getText().isEmpty() || puntaje > 100 || puntaje < 0) {
                jTfPuntaje.setBorder(border);
            }
        } catch (NumberFormatException ex) {
            jTfPuntaje.setBorder(border);

        }
        if (jTaComentario.getText().isEmpty()) {
            jTaComentario.setBorder(border);
        }

        if (jLEvaluador.isSelectionEmpty()) {
            jLEvaluador.setBorder(border);
        }
        if (jLPostulante.isSelectionEmpty()) {
            jLPostulante.setBorder(border);
        }
    }

    private void txtVacio() {
        jLabelEvaluador.setText("");
        jLabelPostulante1.setText("");
        jTfPuntaje.setText("");
        jTaComentario.setText("");
        jLEvaluador.clearSelection();
        jLPostulante.clearSelection();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelEvaluador;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBIngresa;
    private javax.swing.JList<Object> jLEvaluador;
    private javax.swing.JList<Object> jLPostulante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEvaluador;
    private javax.swing.JLabel jLabelException;
    private javax.swing.JLabel jLabelPostulante1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTaComentario;
    private javax.swing.JTextField jTfPuntaje;
    // End of variables declaration//GEN-END:variables

   
}
