
package Interfaz;

import Dominio.Sistema;
import java.io.EOFException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class inicio extends javax.swing.JPanel {

    private Sistema modelo;
    private Menu menu;
    private boolean cargarDatos = false;

    
    public inicio() {
        modelo = new Sistema();
        initComponents();
    }

    public inicio(Sistema miModelo, Menu miMenu) {
        setMenu(miMenu);
        this.modelo = miModelo;
        initComponents();
        jProgressBarCar.setVisible(false);
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        btnCont = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jProgressBarCar = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTION DE PERSONAL");

        btnCargar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCargar.setText("Cargar Datos Guardados");
        btnCargar.setToolTipText("");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnCont.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCont.setText("Continuar Desde Un Sistema Vacio");
        btnCont.setToolTipText("");
        btnCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnReset.setText("Resetear");
        btnReset.setToolTipText("");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jProgressBarCar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jProgressBarCarComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBarCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addComponent(btnCont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnCont, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

        try {
            jProgressBarCar.setMinimum(0);
            jProgressBarCar.setMaximum(100);
            jProgressBarCar.setVisible(true);
            jProgressBarCar.setValue(0);
            ObjectInputStream in = new ObjectInputStream(Files.newInputStream(Paths.get("data.txt")));
            Sistema miModelo = (Sistema) in.readObject();
            modelo = miModelo;
            if (miModelo.sistemaEstaVacio()) {
                JOptionPane.showMessageDialog(this, "No hay nada guardado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

            } else {
                jProgressBarCar.setValue(50);
                this.menu.setModelo(miModelo);
                Menu menu = new Menu(miModelo);
                this.setMenu(menu);
                jProgressBarCar.setValue(100);
                cargarDatos = true;
            }

        } catch (EOFException exEOF) {
            JOptionPane.showMessageDialog(this, "No hay nada guardado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContActionPerformed
        // TODO add your handling code here:
        if (!cargarDatos||modelo.sistemaEstaVacio()) {
            modelo.vaciarListas();
            registroTematica v = new registroTematica(modelo);
            menu.agregarPanel(v);
        } 
       
    }//GEN-LAST:event_btnContActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        Object[] opciones = {"Resetar", "Cancelar"};
        String mensaje = "Si resetea el sistema se borraran todos los datos ";
        int opcionSeleccionada = JOptionPane.showOptionDialog(menu,
                mensaje,
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones, opciones[1]);
        if (opcionSeleccionada == 0) {
            modelo.resetearSistema();
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void jProgressBarCarComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jProgressBarCarComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBarCarComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCont;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBarCar;
    // End of variables declaration//GEN-END:variables
}
