
package Interfaz;

import Dominio.Sistema;

import Exceptions.Exception_ParseNumero;
import Exceptions.Exception_StringVacio;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;

public class registroEvaluador extends javax.swing.JPanel {

    private Sistema modelo;

 
    public registroEvaluador() {
        initComponents();
    }

    public registroEvaluador(Sistema miModelo) {
        this.modelo = miModelo;
        initComponents();
        jLabeExcep1.setVisible(false);
        jLabelExcep2.setVisible(false);
        jLabelException.setVisible(false);
    }

    public boolean esCedulaValida(String id) {
        boolean res = true;
        for (int i = 0; i < modelo.getListaEvaluadores().size(); i++) {
            if (String.valueOf(modelo.getListaEvaluadores().get(i).getId()).equals(id)) {
                res = false;
            }
        }
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtId = new javax.swing.JTextField();
        jtxtDir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtAñoIn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jBRegistrar = new javax.swing.JToggleButton();
        jtxtNombre = new javax.swing.JTextField();
        jLabelException = new javax.swing.JLabel();
        jLabeExcep1 = new javax.swing.JLabel();
        jLabelExcep2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(850, 880));

        jtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdActionPerformed(evt);
            }
        });

        jtxtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro Evaluador");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 20));

        jtxtAñoIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAñoInActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cédula:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Dirección:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Año de Ingreso:");

        jBCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBRegistrar.setText("Registrar");
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });

        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });

        jLabelException.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelException.setText("jLabel4");

        jLabeExcep1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabeExcep1.setText("blank");

        jLabelExcep2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelExcep2.setText("blank");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtId)
                                    .addComponent(jtxtAñoIn)
                                    .addComponent(jtxtNombre)
                                    .addComponent(jtxtDir, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabeExcep1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelExcep2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabelException, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabeExcep1)))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtAñoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExcep2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabelException, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistrar)
                    .addComponent(jBCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdActionPerformed

    private void jtxtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDirActionPerformed

    private void jtxtAñoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAñoInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAñoInActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        Object[] opciones = {"Ok", "Cancelar"};
        String mensaje = "Si cancela se borraran todos los datos ";
        int opcionSeleccionada = JOptionPane.showOptionDialog(this,
                mensaje,
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones, opciones[1]);
        if (opcionSeleccionada == 0) {
            txtVacio();

        }

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarActionPerformed
        if (esCedulaValida(jtxtId.getText()) && (Integer.parseInt(jtxtAñoIn.getText()) <= 2023)) {
            setLabelExceptionVisible();
            String nombre = jtxtNombre.getText();
            String id = jtxtId.getText();
            String direccion = jtxtDir.getText();
            String añoIn = jtxtAñoIn.getText();
            setDefaultBorder();
            try {
                modelo.registrarEvaluador(nombre, id, direccion, añoIn);
                txtVacio();
            } catch (Exception_StringVacio ex) {
                Border border = BorderFactory.createLineBorder(Color.RED, 2);
                checkAndSetBorder(border);
                jLabelException.setVisible(true);
                jLabelException.setText("Complete las áreas indicadas");
            } catch (Exception_ParseNumero ex) {
                jLabeExcep1.setText("Debe Ingresar un número");
                jLabeExcep1.setVisible(true);
                jLabelExcep2.setText("Debe Ingresar un número");
                jLabelExcep2.setVisible(true);
            }
        } else {
            if (!esCedulaValida(jtxtId.getText())) {
                JOptionPane.showMessageDialog(null, "Error: Ya hay un evaluador con esa cedula");

            }
            if ((Integer.parseInt(jtxtAñoIn.getText()) <= 2023)) {
                JOptionPane.showMessageDialog(null, "Ingrese una fecha anterior o igual a 2023");
            }

        }
    }//GEN-LAST:event_jBRegistrarActionPerformed
    private void txtVacio() {
        jtxtNombre.setText("");
        jtxtId.setText("");
        jtxtDir.setText("");
        jtxtAñoIn.setText("");
    }

    private void checkAndSetBorder(Border border) {
        if (jtxtNombre.getText().equals("")) {
            jtxtNombre.setBorder(border);
        }
        if (jtxtDir.getText().equals("")) {
            jtxtDir.setBorder(border);
        }
        if (jtxtId.getText().equals("")) {
            jtxtId.setBorder(border);
        }
        if (jtxtAñoIn.getText().equals("")) {
            jtxtAñoIn.setBorder(border);
        }
    }
    
    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed
    
    private void setLabelExceptionVisible() {
        jLabeExcep1.setVisible(false);
        jLabelExcep2.setVisible(false);
        jLabelException.setVisible(false);
    }

    private void setDefaultBorder() {
        jtxtNombre.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtxtDir.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtxtId.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtxtAñoIn.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JToggleButton jBRegistrar;
    private javax.swing.JLabel jLabeExcep1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelExcep2;
    private javax.swing.JLabel jLabelException;
    private javax.swing.JTextField jtxtAñoIn;
    private javax.swing.JTextField jtxtDir;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
}
